services:
  server:
    container_name: validator-api
    build:
      context: backend/
    volumes:
      - ./backend/:/app/:rw
    environment:
      - ENVIRONMENT=development
      - CORS_ENABLED=False
      - LOG_LEVEL=Debug

  proxy:
    container_name: nginx-proxy
    build:
      context: nginx/
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw

