services:
  server:
    container_name: validator-api
    image: docker.io/santlink/validator-api:${TAG-API}
    restart: unless-stopped

  proxy:
    container_name: nginx-proxy
    image: docker.io/santlink/validator-proxy:${TAG-PROXY}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"

