name: CI-CD

on:
  push:
    branches: [ "test","main" ]
  pull_request:
    branches: [ "test","main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/validator-api

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker
      uses: docker/setup-buildx-action@v4.2.0

    - name: Docker meta api
      id: meta-validator-api
      uses: docker/metadata-action@v6
      with:
        images: santlink/validator-api
    - name: Docker meta proxy
      id: meta-validator-proxy
      uses: docker/metadata-action@v6
      with:
        images: santlink/validator-proxy

    - name: Login registry
      uses: docker/login-action@v4.6.0
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Build and push validator-api image
      uses: docker/build-push-action@v7.3.0
      with:
        context: project/backend
        file: project/backend/Dockerfile
        push: true
        labels: ${{ steps.meta-validator-api.outputs.labels }}
        tags: ${{ steps.meta-validator-api.outputs.tags }}
    - name: Build and push proxy-nginx image
      uses: docker/build-push-action@v7.3.0
      with:
        context: project/nginx
        file: project/nginx/Dockerfile
        push: true
        labels: ${{ steps.meta-validator-proxy.outputs.labels }}
        tags: ${{ steps.meta-validator-proxy.outputs.tags }}

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup ssh
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-port: ${{ secrets.SSH_PORT }}
      - name: scp compose file to remote server
        run: | 
          scp app.sh project/compose.yml project/.env.testing project/.env.testing ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/user/app/
      - name: run app on remote server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/user/app && bash app.sh start --testing"
    
      